---
title: "Responses to Reviewers"
author: "Camila Vargas"
date: "3/25/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(readxl) 
library(freeR)
library(RColorBrewer)
```

## Read data
```{r}

## the csv file is the most complete raw data set
raw_data <- read_csv("data/vargas_gender_data_raw.csv")

##organization gender composition
gender_comp <- read_csv("data/org_gender_composition.csv")
```

## Plot % of women vs cooperation results
In addition, with your data, can you plot a figure with the % of women in x axis, and the cooperation variable in y axis? is there a pattern?

```{r}
## Preparing data
coop_summary <- raw_data %>% 
  group_by(organization) %>% 
  summarise(coop_avg = mean(cooperation)) %>% 
  ungroup() %>% 
  left_join(gender_comp, by = "organization") %>% 
  mutate(prop_wom = (women_participants/tot_participants))

## plot

##colors
org_cols <- 23
my_colors <- colorRampPalette(brewer.pal(8, "Set2"))(org_cols)
my_colors_2 <- colorRampPalette(brewer.pal(12, "Paired"))(org_cols)


coop_summary %>% 
  ggplot() +
  geom_smooth(method = "lm", se = FALSE,
              aes(x = prop_wom, y = coop_avg))+
  geom_point(aes(x = prop_wom, y = coop_avg, color = organization))+
  geom_text(aes(x = prop_wom, y = coop_avg, label = organization), size = 3, check_overlap = T)+
  scale_color_manual(values = my_colors_2)+
  theme_classic(base_size = 18)+
  scale_x_continuous(labels = scales::percent, name = "Percentage of Women")+
  scale_y_continuous(breaks = seq(0,20, 2), name = "Cooperation")+
  theme(legend.position = "none")

```


## Variability within organizations

```{r}
var_check <- raw_data %>% 
  select(organization, type_organization, 15:22) %>% 
  pivot_longer(cols = 3:10,
               names_to = "variable",
               values_to = "value") %>% 
  mutate(organization = recode(organization,
                              "AnahuacMix" = "Anahuac",
                              "AnahuacWom" = "Anahuac",
                              "ColiumoMen" = "Coliumo",
                              "ColiumoWom" = "Coliumo",
                              "Lo Roja" = "Coronel",
                              "MauleMen" = "Coronel",
                              "MauleWomen" = "Coronel",
                              "PichilemuFar" = "Pichilemu",
                              "PichilemuMen" = "Pichilemu",
                              "PichilemuWom" = "Pichilemu"))

men_plot <- var_check %>% 
  filter(type_organization == "Men") %>% 
  ggplot(aes(y = value, x = variable))+
  geom_boxplot(fill = "gray")+
  theme_classic()+
  coord_flip()+
  #theme(axis.text.x = element_text(angle = 90))+
  facet_wrap(~organization)+
  ggtitle("Only Men Organizations")


women_plot <- var_check %>% 
  filter(type_organization == "Women") %>% 
  ggplot(aes(y = value, x = variable))+
  geom_boxplot(fill = "gray")+
  theme_classic()+
  coord_flip()+
  #theme(axis.text.x = element_text(angle = 90))+
  facet_wrap(~organization)+
  ggtitle("Only Women Organizations")


mixedW_plot <- var_check %>% 
  filter(type_organization == "MixedW") %>% 
  ggplot(aes(y = value, x = variable))+
  geom_boxplot(fill = "gray")+
  theme_classic()+
  coord_flip()+
  #theme(axis.text.x = element_text(angle = 90))+
  facet_wrap(~organization)+
  ggtitle("Mixed-W Organizations")


mixedM_plot <- var_check %>% 
  filter(type_organization == "MixedM") %>% 
  ggplot(aes(y = value, x = variable))+
  geom_boxplot(fill = "gray")+
  theme_classic()+
  coord_flip()+
  #theme(axis.text.x = element_text(angle = 90))+
  facet_wrap(~organization)+
  ggtitle("Mixed-M Organizations")


sup_fig <- women_plot/men_plot/mixedW_plot/mixedM_plot

var_fig <- plot_grid(women_plot,men_plot, mixedW_plot, mixedM_plot, nrow = 4, align = "v", rel_widths = c(1, -0.1, 1))

```








